# Generated by Django 3.1.2 on 2021-03-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LED_Strip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colour',
            name='name',
            field=models.CharField(default='EMPTY', max_length=200),
            preserve_default=False,
        ),
    ]
